HW-23/scrapper_app/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('view-cart/', views.view_cart, name='view_cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('delete-from-cart/', views.delete_product_from_cart, name='delete-from-cart'),
    path('change-cart/', views.change_product_quantity, name='change-cart'),
    path('api/cart-quantity/', views.cart_quantity, name='api-cart-quantity')
]

HW-23/scrapper_app/scrapper/urls.py
from django.urls import path

from . import views


app_name = 'scrapper'
urlpatterns = [
    path('add-products/', views.page_add_products, name='add_products'),
    path('my-products/', views.page_my_products, name='my_products'),
    path('products/cat/<int:cat_id>', views.page_products_by_cat, name='products_by_cat'),
    path('product/<int:item_id>/', views.page_product, name='product'),
    path('login/', views.page_login, name='login'),
    path('logout/', views.page_logout, name='logout'),
    path('product/<int:product_id>/delete', views.page_delete_product, name='delete_product'),
    path('product/<int:product_id>/edit', views.page_edit_product, name='edit_product'),
    path('api/products/', views.ProductListApi.as_view(), name='api_products_list'),
    path('api/product/<int:product_id>/', views.ProductDetailsApi.as_view(), name='api_products_details'),
    path('api/categories/', views.CategoryListApi.as_view(), name='api_categories_list'),
    path('api/id-srorage/', views.IdStorageListApi.as_view(), name='api_id_storage')
]

HW-23/scrapper_app/scrapper_app/urls.py
from django.contrib import admin
from django.urls import include, path

from scrapper import views # noqa

urlpatterns = [
    path('', views.page_my_products, name='my_products'),
    path('scrapper/', include('scrapper.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
]

HW-23/scrapper_app/cart/models.py
from django.db import models

# Create your models here.

HW-23/scrapper_app/scrapper/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import IdStorage, Product


class ProductForm(ModelForm):
    class Meta:
        model = IdStorage
        fields = ['product_ids']
        labels = {'product_ids': 'List of products ids:'}


class AddProductToCart(Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(
        validators=(MinValueValidator(1),
                    MaxValueValidator(20)
                    )
    )


class ProductDelete(Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput())


class LoginForm(Form):
    username = forms.CharField(max_length=200)
    password = forms.CharField(min_length=4, max_length=20, widget=forms.PasswordInput())


class ProductEdit(ModelForm):
    class Meta:
        model = Product
        fields = [
            'item_id',
            'title',
            'href',
            'current_price',
            'old_price',
            'brand',
            'category',
            'sell_status'
        ]

HW-23/scrapper_app/cart/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.http.response import JsonResponse

from scrapper.forms import AddProductToCart, ProductDelete # noqa
from scrapper.models import Product # noqa


def view_cart(request):
    cart = request.session.get('cart', {})
    context = {'cart': cart}
    total_sum = 0
    if cart:
        products = Product.objects.filter(id__in=cart.keys()).values()

        if products:
            products_list = [product for product in products]
            for product in products_list:
                product['quantity'] = cart[str(product['id'])]
                product['sum'] = int(product['quantity']) * int(product['current_price'])
                product['delete_product'] = ProductDelete(
                    initial={'item_id': product['id']}
                )
                product['form_change_cart'] = AddProductToCart(
                    initial={'product_id': product['id'],
                             'quantity': product['quantity']
                             }
                )

            total_sum = sum([product['sum'] for product in products_list])

        context = {'products': products,
                   'cart': cart,
                   'total_sum': total_sum
                   }
    else:
        context = {
                   'cart': cart,
                   'total_sum': total_sum
                   }
    return render(request, 'view_cart.html', context=context)


@require_http_methods(['POST'])
def add_to_cart(request):
    form = AddProductToCart(request.POST)

    if form.is_valid():
        data = form.cleaned_data
        cart = request.session.setdefault('cart', {})

        cart.setdefault(str(data['product_id']), 0)
        cart[str(data['product_id'])] += data['quantity']

        request.session_modified = True
        request.session.save()
        return JsonResponse({'message': 'Product was added to cart', 'cart_quantity': sum(cart.values())})
    else:
        return JsonResponse({'message': 'Form is not valid'}, status=400)


@require_http_methods(['POST'])
def clear_cart(request):
    if 'cart' in request.session:
        del request.session['cart']
        request.session.save()
    return JsonResponse({'message': 'Cart was cleared', 'cart_quantity': 0, 'total_sum': 0})


@require_http_methods(['POST'])
def delete_product_from_cart(request):
    form = ProductDelete(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        cart = request.session.setdefault('cart', {})
        del cart[str(data['item_id'])]
        request.session.save()
        return JsonResponse({'message': 'Product was deleted', 'cart_quantity': sum(cart.values())})


@require_http_methods(['POST'])
def change_product_quantity(request):
    change_form = AddProductToCart(request.POST)

    if change_form.is_valid():
        data = change_form.cleaned_data
        cart = request.session.setdefault('cart', {})

        products = Product.objects.filter(id__in=cart.keys()).values()
        products_list = [product for product in products]
        for product in products_list:
            product['quantity'] = cart[str(product['id'])]
            product['sum'] = int(data['quantity']) * int(product['current_price'])

        total_sum = sum([product['sum'] for product in products_list])
        cart[str(data['product_id'])] = data['quantity']
        request.session.save()
        return JsonResponse({
            'message': 'Product`s quantity was changed',
            'cart_quantity': sum(cart.values()),
            'total_sum': total_sum
        })


def cart_quantity(request):
    cart = request.session.get('cart', {})
    return JsonResponse({'cart_quantity': sum(cart.values())})

HW-23/scrapper_app/cart/templates/view_cart.html
{% load static %}

<link rel="stylesheet" href="{% static 'scrapper/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<header>
    <a href="{% url 'scrapper:add_products' %}">Add new products</a> |
    <a href="{% url 'scrapper:my_products' %}">My products</a> |
    <a href="{% url 'cart:view_cart' %}">Cart
        (<span id="cart_quantity"></span>)
    </a>
</header>

{% block content %}
    <h1>My cart</h1>

    <p id="messages"></p>

    <div class="edit_cart_block clear_cart_block">
        {% csrf_token %}
        <button type="submit" id="clear_cart_button">Clear cart</button>
    </div>

    <div id="cart_products">
        {% for product in products %}
            <div class="product_item product_item_{{ product.id }}">
                <div class="product_id">
                    <span class="label">ID:</span>
                    {{ product.item_id }}
                </div>
                <div class="product_title">
                    <span class="label">Title:</span>
                    {{ product.title }}
                </div>
                <div class="product_price">
                    <span class="label">Price:</span>
                    {{ product.current_price }}
                    <span class="price_cur">UAH</span>
                </div>
                <div class="product_quantity">
                    <div class="edit_cart_block change_quantity_block">
                        {% csrf_token %}
                        {{ product.form_change_cart }}

                        <button
                                type="submit"
                                id="change_quantity_button"
                                data_product_id="{{ product.id }}"
                                data_new_quantity="{{ product.quantity }}"
                                data_price="{{ product.current_price }}">
                            Change quantity
                        </button>
                    </div>
                    <div class="product_sum">
                        <span class="label">Sum:</span>
                        <span class="current_sum">{{ product.sum }}</span>
                        <span class="price_cur">UAH</span>
                    </div>
                </div>

                <div class="edit_cart_block delete_product_block">
                    {% csrf_token %}
                    {{ product.delete_product }}
                    <button
                            type="submit"
                            id="delete_product_button"
                            data_product_id="{{ product.id }}">
                        Delete product
                    </button>
                </div>
                <br>
            </div>

            {% empty %}
            <p>Your cart is empty</p>

        {% endfor %}

    </div>

    <div class="total_sum">
        <span class="label">Total:</span>
        <span class="total_sum_number">{{ total_sum }}</span>
        <span class="price_cur">UAH</span>
    </div>

{% endblock content %}

<script>
    $(document).ready(function () {
        {#Show total quantity#}
        $.ajax({
            url: "{% url 'cart:api-cart-quantity' %}",
            method: "GET",
            success: function (result) {
                $("#cart_quantity").html(result.cart_quantity);
            }
        });

        {#Change quantity#}
        $(document).on('click', '#change_quantity_button', function (){
            var data_product_id = $(this).attr("data_product_id")
            $(this).attr('data_new_quantity', $(this).parent().find('#id_quantity').val())
            var data_new_quantity = $(this).attr("data_new_quantity")
            var price = $(this).attr('data_price')
            var price_sum = price * data_new_quantity
            var current_sum = $(this).parent().parent().find('.current_sum')
            var current_button = $(this)

            $.ajax({
                url: '{% url 'cart:change-cart' %}',
                method: 'POST',
                data: {
                    quantity: data_new_quantity,
                    product_id: data_product_id
                },
                beforeSend: function (xhr) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                },
                success: function(result){
                    $("#cart_quantity").html(result.cart_quantity);
                    current_button.html(result.message);
                    $(".total_sum_number").html(result.total_sum);
                    current_sum.html(price_sum)
                    setTimeout(function (){
                        current_button.html('Change quantity');
                    }, 2000)
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }

            });
        })


        {#Delete product#}
        $(document).on('click', '#delete_product_button', function (){
            var data_product_id = $(this).attr("data_product_id")
            console.log(data_product_id);
            $.ajax({
                url: '{% url 'cart:delete-from-cart' %}',
                method: 'POST',
                type: 'DELETE',
                data: {
                    item_id: data_product_id
                },
                beforeSend: function (xhr) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                },
                success: function(result) {
                    $("#cart_quantity").html(result.cart_quantity);
                    $("div").remove(".product_item_" + data_product_id);
                    $("#messages").html(result.message);
                    setTimeout(function (){
                        $("#messages").html(' ');
                    }, 2000)
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        })

        {#Clear cart#}
        $(document).on('click', '#clear_cart_button', function (){
            $.ajax({
                url: '{% url 'cart:clear_cart' %}',
                method: 'POST',
                beforeSend: function (xhr) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                },
                success: function(result) {
                    $("#cart_quantity").html(result.cart_quantity);
                    $(".total_sum_number").html(result.total_sum);
                    $("#messages").html(result.message);
                    $("div").remove(".product_item");
                    setTimeout(function (){
                        $("#messages").html(' ');
                    }, 2000)
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        })

    })
</script>