HW-23/scrapper_app/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('view-cart/', views.view_cart, name='view_cart'),
    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('delete-from-cart/', views.delete_product_from_cart, name='delete-from-cart'),
    path('change-cart/', views.change_product_quantity, name='change-cart'),
    path('api/cart-quantity/', views.cart_quantity, name='api-cart-quantity')
]

HW-23/scrapper_app/scrapper/urls.py
from django.urls import path

from . import views


app_name = 'scrapper'
urlpatterns = [
    path('add-products/', views.page_add_products, name='add_products'),
    path('my-products/', views.page_my_products, name='my_products'),
    path('products/cat/<int:cat_id>', views.page_products_by_cat, name='products_by_cat'),
    path('product/<int:item_id>/', views.page_product, name='product'),
    path('login/', views.page_login, name='login'),
    path('logout/', views.page_logout, name='logout'),
    path('product/<int:product_id>/delete', views.page_delete_product, name='delete_product'),
    path('product/<int:product_id>/edit', views.page_edit_product, name='edit_product'),
    path('api/products/', views.ProductListApi.as_view(), name='api_products_list'),
    path('api/product/<int:product_id>/', views.ProductDetailsApi.as_view(), name='api_products_details'),
    path('api/categories/', views.CategoryListApi.as_view(), name='api_categories_list'),
    path('api/id-srorage/', views.IdStorageListApi.as_view(), name='api_id_storage')
]

HW-23/scrapper_app/scrapper_app/urls.py
from django.contrib import admin
from django.urls import include, path

from scrapper import views # noqa

urlpatterns = [
    path('', views.page_my_products, name='my_products'),
    path('scrapper/', include('scrapper.urls')),
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
]

HW-23/scrapper_app/scrapper/models.py
from django.db import models


class IdStorage(models.Model):
    product_ids = models.TextField()

    def __str__(self):
        return self.product_ids


class Category(models.Model):
    category_title = models.TextField(max_length=50, default='0')

    def __str__(self):
        return self.category_title


class Product(models.Model):
    item_id = models.CharField(max_length=20, default='No id')
    title = models.CharField(max_length=200, default='No title')
    href = models.CharField(max_length=200, default='No link')
    current_price = models.CharField(max_length=10, default='0')
    old_price = models.CharField(max_length=10, default='0')
    brand = models.CharField(max_length=50, default='No brand')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='0')
    sell_status = models.CharField(max_length=20, default='Unknown')

HW-23/scrapper_app/scrapper/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.core.validators import MinValueValidator, MaxValueValidator

from .models import IdStorage, Product


class ProductForm(ModelForm):
    class Meta:
        model = IdStorage
        fields = ['product_ids']
        labels = {'product_ids': 'List of products ids:'}


class AddProductToCart(Form):
    product_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(
        validators=(MinValueValidator(1),
                    MaxValueValidator(20)
                    )
    )


class ProductDelete(Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput())


class LoginForm(Form):
    username = forms.CharField(max_length=200)
    password = forms.CharField(min_length=4, max_length=20, widget=forms.PasswordInput())


class ProductEdit(ModelForm):
    class Meta:
        model = Product
        fields = [
            'item_id',
            'title',
            'href',
            'current_price',
            'old_price',
            'brand',
            'category',
            'sell_status'
        ]

HW-23/scrapper_app/scrapper/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, IsAdminUser

from .forms import ProductForm, AddProductToCart, LoginForm, ProductEdit
from .models import Product, Category, IdStorage
from .serializers import ProductSerializer, CategorySerializer, IdStorageSerializer
from .tasks import get_and_save_items


def page_add_products(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        product_ids = request.POST.get('product_ids')
        form.save()
        get_and_save_items.delay(product_ids)
        
    else:
        form = ProductForm()
    return render(request, 'add_products.html', {'form': form})


def page_my_products(request):
    categories = Category.objects.all()
    items_list = Product.objects.all()
    context = {
        "categories": categories,
        'items_list': items_list
    }
    return render(request, "my_products.html", context)


def page_products_by_cat(request, cat_id):
    all_categories = Category.objects.all()
    chosen_category = Category.objects.get(id=cat_id)
    products = Product.objects.filter(category__id=cat_id)
    context = {
        "categories": all_categories,
        'chosen_category': chosen_category,
        'products': products
    }

    return render(request, "products_by_cat.html", context)


def page_product(request, item_id):
    product = get_object_or_404(Product, id=item_id)
    category = Category.objects.get(id=product.category_id)

    form_cart = AddProductToCart(
        initial={'product_id': product.id,
                 'quantity': 1
                 }
    )
    context = {
        'product': product,
        'form': form_cart,
        'category': category
    }

    return render(request, 'product.html', context)


def page_login(request):
    logout(request)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/scrapper/my-products/')
            else:
                messages.error(request, 'Sorry, that login was invalid. Please try again.')
                return render(request, 'login.html', {"form": form})
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def page_logout(request):
    logout(request)
    return redirect('/scrapper/my-products/')


@login_required()
def page_delete_product(request, product_id):
    context = {}
    if request.user.is_superuser:
        product = get_object_or_404(Product, id=product_id)
        if request.method == 'POST':
            product.delete()
            return redirect('/scrapper/my-products/')
    else:
        messages.error(request, 'Wrong access level!')
        return redirect('/scrapper/my-products/')

    return render(request, 'delete_product.html', context)


@login_required()
def page_edit_product(request, product_id):
    context = {}
    if request.user.is_superuser:
        product = get_object_or_404(Product, id=product_id)
        form = ProductEdit(request.POST or None, instance=product)

        if form.is_valid():
            form.save()
            return redirect('/scrapper/my-products/')

        context['form'] = form
    else:
        messages.error(request, 'Wrong access level!')
        return redirect('/scrapper/my-products/')

    return render(request, "edit_product.html", context)


class ProductPagination(PageNumberPagination):
    page_size = 5


class ProductListApi(ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    pagination_class = ProductPagination


class ProductDetailsApi(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = (IsAdminUser,)

    def get_permissions(self):
        if self.request.method in ['PUT', 'DELETE']:
            return [IsAdminUser()]
        return [IsAuthenticated()]

    def get(self, response, product_id):
        product = get_object_or_404(Product, id=product_id)
        serializer = ProductSerializer(product)
        return Response(serializer.data)

    def delete(self, response, product_id):
        product = get_object_or_404(Product, id=product_id)
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    def put(self, request, product_id, format=None):
        product = get_object_or_404(Product, id=product_id)
        serializer = ProductSerializer(product, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CategoryListApi(ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class IdStorageListApi(ListAPIView):
    queryset = IdStorage.objects.all()
    serializer_class = IdStorageSerializer

HW-23/scrapper_app/scrapper/templates/add_products.html
{% extends "my_products.html" %}

{% block content %}
    <div class="container">
        <form method="POST">
          <fieldset>
            <legend>Add products IDs, each from new line: </legend>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </fieldset>
        </form>
    </div>
{% endblock content %}

HW-23/scrapper_app/scrapper/templates/delete_product.html
{% block content %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        Are you want to delete this item ?

        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>
{% endblock content %}

HW-23/scrapper_app/scrapper/templates/edit_product.html
{% block content %}
<div class="main">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Update">
    </form>
</div>
{% endblock content %}

HW-23/scrapper_app/scrapper/templates/login.html
{% extends "my_products.html" %}

{% block content %}
<div class="login_block">
    <form class="login_form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        {% for message in messages %}
        <div class="alert alert-success">
               {{ message }}
        </div>
        {% endfor %}

        <button type="submit">Login</button>
    </form>
</div>
{% endblock content %}

HW-23/scrapper_app/scrapper/templates/my_products.html
{% load static %}

<link rel="stylesheet" href="{% static 'scrapper/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<header>
    {%  if request.user.is_superuser %}
    <a href="{% url 'scrapper:add_products' %}">Add new products</a> |
    {% endif %}

    <a href="{% url 'scrapper:my_products' %}">My products</a> |

    {% if request.user.is_authenticated %}
    <a href="{% url 'cart:view_cart' %}">Cart
        (<span id="cart_quantity"></span>)
    </a>
    {% endif %}

    <span class="login">
        {% if request.user.is_authenticated %}
            {%  if request.user.is_superuser %}
                Hello, {{ request.user.get_username }} |
                <a href="{% url 'admin:index' %}">Admin Panel</a> |
            {% else %}
                Hello, {{ request.user.get_username }} |
            {% endif %}
            <a href="{% url 'scrapper:logout' %}">Logout</a>
        {% else %}
            Hello, guest |
            <a href="{% url 'scrapper:login' %}">Login</a>
        {% endif %}
    </span>
</header>

{% block content %}
    {% for message in messages %}
        <div class="alert alert-success">
               {{ message }}
        </div>
    {% endfor %}

    <div class="block_categories">
        <p>All categories:</p>
        {% for category in categories %}
            <ul class="categories">
                <li class="title">
                    <a href="{% url 'scrapper:products_by_cat' category.id %}">{{ category.category_title }}</a>
                </li>
            </ul>
        {% endfor %}
    </div>

    <h2>All products:</h2>

    <div class="container">
        {% for item in items_list %}
            <div class="product_item">
                <div class="title">
                    <span class="label">Product title:</span>
                    {{ item.title }}
                </div>
                <div class="price">
                    <span class="label">Price:</span>
                    {{ item.current_price }}
                </div>
                <div class="sell_status">
                    <span class="label">Status:</span>
                    {% if item.sell_status == 'available' %}
                    <span class="in_stock">In stock</span>
                    {% else %}
                    <span class="not_in_stock">Not in stock</span>
                    {% endif %}
                </div>
                <div class="more">
                    <a href="{% url 'scrapper:product' item.id %}">View more</a>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock content %}

<script>
    $(document).ready(function(){
      $.ajax({url: "{% url 'cart:api-cart-quantity' %}",
          method: "GET",
          success: function(result){
          $("#cart_quantity").html(result.cart_quantity);
      }});
    })
</script>

HW-23/scrapper_app/scrapper/templates/product.html
{% extends "my_products.html" %}

{% block content %}
<h1>Product details:</h1>

<div class="container">
    <div class="product_item">
        <div class="item_id">
            <span class="label">ID:</span>
            {{ product.item_id }}
        </div>
        <div class="title">
            <span class="label">Product title:</span>
            {{ product.title }}
        </div>
        <div class="link">
            <span class="label">Link to item:</span>
            <a href="{{product.href}}">{{ product.href }}</a>
        </div>
        <div class="old_price">
            <span class="label">Old price:</span>
            {{ product.old_price }}
            <span class="price_cur">UAH</span>
        </div>
        <div class="current_price">
            <span class="label">Current price:</span>
            {{ product.current_price }}
            <span class="price_cur">UAH</span>
        </div>
        <div class="brand">
            <span class="label">Brand:</span>
            {{ product.brand }}
        </div>
        <div class="category">
            <span class="label">Category:</span>
            {{ category.category_title }}
        </div>
        <div class="sell_status">
            <span class="label">Status:</span>
            {% if product.sell_status == 'available' %}
            <span class="in_stock">In stock</span>
            {% else %}
            <span class="not_in_stock">Not in stock</span>
            {% endif %}
        </div>
        {% if request.user.is_superuser %}
        <div class="admin_block">
            <div class="admin_link edit">
                <a href="{% url 'scrapper:edit_product' product_id=product.id %}">Edit product</a>
            </div>
            <div class="admin_link delete">
                <a href="{% url 'scrapper:delete_product' product_id=product.id %}">Delete product</a>
            </div>
        </div>
        {% endif %}

        {% if product.sell_status == 'available' and request.user.is_authenticated %}
        <div class="cart_block">
{#            <form action="{% url 'cart:add_to_cart' %}" method="POST">#}
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" id="add_to_cart_button">Add to cart</button>
{#            </form>#}
        </div>
        {% endif %}

    </div>

</div>

<script>
    $(document).ready(function(){
        $(document).on('click', '#add_to_cart_button', function (){
            $.ajax({
                url: "{% url 'cart:add_to_cart' %}",
                method: "POST",
                data: {
                    quantity: $("#id_quantity").val(),
                    product_id: $("#id_product_id").val()
                },
                beforeSend: function (xhr) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                },
                success: function(result){
                    $("#cart_quantity").html(result.cart_quantity);
                    $("#add_to_cart_button").html(result.message);
                    setTimeout(function (){
                        $("#add_to_cart_button").html('Add to cart');
                    }, 2000)
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        })
    })
</script>

{% endblock content %}

HW-23/scrapper_app/scrapper/templates/products_by_cat.html
{% extends "my_products.html" %}

{% block content %}
    <div class="block_categories">
        <a href="{% url 'scrapper:my_products' %}">Back to all categories</a>
        {% for category in categories %}
        <ul class="categories">
            <li class="title">
                <a href="{% url 'scrapper:products_by_cat' category.id %}">{{ category.category_title }}</a>
            </li>
        </ul>
        {% endfor %}
    </div>

    <h2> {{ chosen_category.category_title }} </h2>

    <div class="container">
        {% for product in products %}
            <div class="product_item">
                <div class="title">
                    <span class="label">Product title:</span>
                    {{ product.title }}
                </div>
                <div class="price">
                    <span class="label">Price:</span>
                    {{ product.current_price }}
                </div>
                <div class="sell_status">
                    <span class="label">Status:</span>
                    {% if product.sell_status == 'available' %}
                    <span class="in_stock">In stock</span>
                    {% else %}
                    <span class="not_in_stock">Not in stock</span>
                    {% endif %}
                </div>
                <div class="more">
                    <a href="{% url 'scrapper:product' product.id %}">View more</a>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock content %}